const {chromium, expect}=require('@playwright/test');
const fs=require('fs');
const path=require('path');
(async()=>{
  const session=JSON.parse(fs.readFileSync(process.env.TAPIN_SESSION_FILE,'utf8'));
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1666,height:1100}});
  await context.addCookies(session.cookies);
  const page=await context.newPage();const errors=[];
  const testName='آزمایش مرورگر '+Date.now();
  page.on('pageerror',e=>errors.push(e.message));
  const out=process.env.TAPIN_ARTIFACTS||path.join(__dirname,'..','artifacts');fs.mkdirSync(out,{recursive:true});
  try{
    await page.goto(session.url+'/wp-admin/admin.php?page=tapin-locator',{waitUntil:'domcontentloaded'});
    await expect(page.locator('.hero-number')).toBeVisible({timeout:20000});
    const invalidNonceStatus=await page.evaluate(async()=>{const r=await fetch(TapinConfig.api+'points',{headers:{'X-WP-Nonce':'invalid'}});return r.status;});
    if(invalidNonceStatus!==403)throw new Error('Invalid REST nonce was not rejected');
    await page.screenshot({path:path.join(out,'dashboard-empty-desktop.png'),fullPage:true});
    await page.locator('.header-actions .text-action').click();
    await expect(page.locator('dialog')).toBeVisible();
    await page.locator('dialog input[name=name]').fill(testName);
    await page.locator('dialog input[name=code]').fill('BROWSER-TEST-'+Date.now());
    await page.locator('dialog input[name=province]').fill('تهران');
    await page.locator('dialog input[name=city]').fill('تهران');
    await page.locator('dialog textarea[name=address]').fill('نشانی آزمایشی مرورگر');
    await page.locator('dialog button[type=submit]').click();
    await expect(page.locator('dialog')).not.toBeVisible();
    await expect(page.locator('table tbody tr').filter({hasText:testName})).toContainText('بدون مختصات');
    const createdId=await page.locator('table tbody tr').filter({hasText:testName}).locator('[data-edit]').getAttribute('data-edit');
    session.test_points=[...(session.test_points||[]),Number(createdId)];fs.writeFileSync(process.env.TAPIN_SESSION_FILE,JSON.stringify(session));
    const row=page.locator('table tbody tr').filter({hasText:testName});
    await row.getByRole('button',{name:'ویرایش',exact:true}).click();
    await page.locator('dialog input[name=latitude]').fill('۳۵٫۷');
    await page.locator('dialog input[name=longitude]').fill('۵۱٫۴');
    await page.locator('dialog button[type=submit]').click();
    await expect(page.locator('dialog')).not.toBeVisible();
    await expect(page.locator('table tbody tr').filter({hasText:testName})).toContainText('ثبت‌شده');
    await page.locator('[data-nav=dashboard]').click();
    await expect(page.locator('.hero-number')).toBeVisible();
    await expect(page.locator('.map-status')).toContainText('نمایش');
    await expect(page.locator('.leaflet-tile-loaded').first()).toBeVisible({timeout:20000});
    await page.screenshot({path:path.join(out,'dashboard-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(out,'dashboard-mobile.png'),fullPage:true});
    const overflow=await page.locator('#tapin-admin').evaluate(el=>el.scrollWidth>el.clientWidth+2);
    if(overflow)throw new Error('Plugin root overflows at mobile width');
    const publicPage=await browser.newPage({viewport:{width:1440,height:1000}});
    await publicPage.goto(session.public_url);
    await expect(publicPage.locator('.tapin-public .map-status')).toContainText('نمایش',{timeout:20000});
    await publicPage.locator('.tapin-public [data-list]').click();
    await publicPage.locator('.map-list button').filter({hasText:testName}).click();
    await expect(publicPage.locator('.leaflet-popup-content')).toContainText('نشانی آزمایشی مرورگر');
    await publicPage.screenshot({path:path.join(out,'public-map.png'),fullPage:true});
    await publicPage.close();
    await page.setViewportSize({width:1666,height:1100});
    await page.locator('[data-nav=points]').click();
    await page.locator('table tbody tr').filter({hasText:testName}).getByRole('button',{name:'حذف',exact:true}).click();
    await page.locator('dialog button[type=submit]').click();
    await expect(page.locator('dialog')).not.toBeVisible();
    await expect(page.locator('table tbody tr').filter({hasText:testName})).toHaveCount(0);
    await page.locator('[data-nav=imports]').click();
    await page.locator('input[type=file]').setInputFiles({name:'browser-check.csv',mimeType:'text/csv',buffer:Buffer.from('name,province,city,address,latitude,longitude\nآزمایش ورود مرورگر,تهران,تهران,نشانی تست,,\nنامعتبر,تهران,تهران,تست,bad,bad\n')});
    await page.locator('#upload-form button[type=submit]').click();
    await expect(page.locator('#mapping-form')).toBeVisible({timeout:20000});
    session.test_jobs.push(Number(new URLSearchParams(page.url().split('?').slice(2).join('?')).get('id')) || Number(page.url().match(/id=(\d+)/)[1]));
    fs.writeFileSync(process.env.TAPIN_SESSION_FILE,JSON.stringify(session));
    await page.screenshot({path:path.join(out,'import-preview.png'),fullPage:true});
    await page.locator('#mapping-form button[type=submit]').click();
    await expect(page.locator('#tapin-content')).toContainText('تکمیل‌شده',{timeout:20000});
    await expect(page.locator('.job-counts')).toContainText('۱');
    await page.screenshot({path:path.join(out,'import-result.png'),fullPage:true});
    await page.locator('[data-nav=providers]').click();
    await expect(page.locator('.provider-cards')).toBeVisible();
    await page.locator('#new-provider').click();
    await page.locator('dialog input[name=name]').fill('ارائه‌دهنده آزمایشی مرورگر');
    await page.locator('dialog input[name=slug]').fill('browser-test-'+Date.now());
    await page.locator('dialog button[type=submit]').click();
    await expect(page.locator('dialog')).not.toBeVisible();
    await page.locator('.provider-cards article').filter({hasText:'ارائه‌دهنده آزمایشی مرورگر'}).getByRole('button',{name:'حذف',exact:true}).click();
    await page.locator('dialog button[type=submit]').click();
    await expect(page.locator('dialog')).not.toBeVisible();
    await page.locator('[data-nav=points]').click();
    await page.locator('table tbody tr').filter({hasText:'آزمایش ورود مرورگر'}).getByRole('button',{name:'حذف',exact:true}).click();
    await page.locator('dialog button[type=submit]').click();
    await expect(page.locator('dialog')).not.toBeVisible();
    if(errors.length)throw new Error(errors.join('\n'));
    console.log('PASS browser: dashboard, create/edit/delete, Persian coordinates, upload/mapping/import results, provider create/delete, mobile overflow, invalid nonce, anonymous public map and popup, no JS errors');
  }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
  finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
